CREATE TABLE IF NOT EXISTS users (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)   NOT NULL,
    email       VARCHAR(512)   NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items (
    id           BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)    NOT NULL,
    description  VARCHAR(1000)   NOT NULL,
    is_available BOOL            NOT NULL,
    owner_id     BIGINT,
    request_id   VARCHAR(1000),
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_items FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id           BIGINT                        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date   TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    end_date     TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    item_id      BIGINT                        NOT NULL,
    booker_id    BIGINT                        NOT NULL,
    status       INTEGER                       NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booking FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_1 FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id           BIGINT                       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(1000)                NOT NULL,
    requestor_id BIGINT                       NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_request FOREIGN KEY (requestor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    id           BIGINT                       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text         VARCHAR(1000)                NOT NULL,
    item_id      BIGINT                       NOT NULL,
    author_name  VARCHAR(255)                 NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
    );