server:
  port: 9090

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:shareit
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  sql:
    init:
      mode: always
---
server:
  port: 9090

spring:
  config:
    activate:
      on-profile: production
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
      show-sql: true