server:
  port: 9090

spring:
  config:
    activate:
      on-profile: test
  datasource:
    # JDBC URL of the database.
    url: jdbc:h2:mem:shareit
    # Login username of the database.
    username: test
    # Login password of the database.
    password: test
    # Fully qualified name of the JDBC driver
    driverClassName: org.h2.Driver
  jpa:
    # Whether to enable logging of SQL statements.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  sql:
    init:
      mode: always
---
server:
  port: 9090

spring:
  config:
    activate:
      on-profile: production
  sql:
    init:
      mode: always
  datasource:
    # Fully qualified name of the JDBC driver
    driver-class-name: org.postgresql.Driver
    # JDBC URL of the database.
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    # Login username of the database.
    username: ${POSTGRES_USER}
    # Login password of the database.
    password: ${POSTGRES_PASSWORD}
  jpa:
    # Whether to enable logging of SQL statements.
    properties:
      hibernate:
        # SQL Dialects.
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        # Pretty print the SQL.
        format_sql: true
    hibernate:
      ddl-auto: none
      show-sql: true